# Data preprocessing

## Importing the libraries

In [321]:
import pandas as pd
import numpy as np

## Obtaining base train and test dataframes

### Creating train and test dataframes

In [322]:
train = pd.read_csv('./application_train.csv')

In [323]:
test = pd.read_csv('application_test.csv')

### Displaying dataframes first lines

In [324]:
train.head()

SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0

[5 rows x 122 columns]

In [325]:
test.head()

SK_ID_CURR  ... AMT_REQ_CREDIT_BUREAU_YEAR
0      100001  ...                        0.0
1      100005  ...                        3.0
2      100013  ...                        4.0
3      100028  ...                        3.0
4      100038  ...                        NaN

[5 rows x 121 columns]

### Moving target to last column in train dataset

In [326]:
target_col = train.pop('TARGET')
train['TARGET'] = target_col

### Dropping unused ID column

In [327]:
train = train.drop(['SK_ID_CURR'], axis=1)
test = test.drop(['SK_ID_CURR'], axis=1)

### Organizing test set columns based on train set column order

In [328]:
test = test[train.drop(['TARGET'], axis=1).columns]
test.head()

NAME_CONTRACT_TYPE  ... AMT_REQ_CREDIT_BUREAU_YEAR
0         Cash loans  ...                        0.0
1         Cash loans  ...                        3.0
2         Cash loans  ...                        4.0
3         Cash loans  ...                        3.0
4         Cash loans  ...                        NaN

[5 rows x 120 columns]

## Taking care of missing data

In [329]:
train.shape

(307511, 121)

In [330]:
test.shape

(48744, 120)

In [331]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
x_dtypes_train = train.dtypes[:-1]
num_cols_train = x_dtypes_train == np.number
X_train = train.iloc[:, :-1].values
imputer.fit(X_train[:, num_cols_train])
X_train[:, num_cols_train] = imputer.transform(X_train[:, num_cols_train])
train.iloc[:, :-1] = X_train
train.head()

NAME_CONTRACT_TYPE CODE_GENDER  ... AMT_REQ_CREDIT_BUREAU_YEAR TARGET
0         Cash loans           M  ...                        1.0      1
1         Cash loans           F  ...                        0.0      0
2    Revolving loans           M  ...                        0.0      0
3         Cash loans           F  ...                        1.0      0
4         Cash loans           M  ...                        0.0      0

[5 rows x 121 columns]

In [332]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
x_dtypes_test = test.dtypes
num_cols_test = x_dtypes_test == np.number
X_test = test.iloc[:, :].values
imputer.fit(X_test[:, num_cols_test])
X_test[:, num_cols_test] = imputer.transform(X_test[:, num_cols_test])
test.iloc[:, :] = X_test
test.head()

NAME_CONTRACT_TYPE  ... AMT_REQ_CREDIT_BUREAU_YEAR
0         Cash loans  ...                        0.0
1         Cash loans  ...                        3.0
2         Cash loans  ...                        4.0
3         Cash loans  ...                        3.0
4         Cash loans  ...                        2.0

[5 rows x 120 columns]

### Get text features Na rows percentage

In [333]:
na_cols_pctg_train = train[train.columns[train.isna().sum() > 0]].isna().sum() / train.shape[0]
na_cols_pctg_train

NAME_TYPE_SUITE        0.004201
OCCUPATION_TYPE        0.313455
FONDKAPREMONT_MODE     0.683862
HOUSETYPE_MODE         0.501761
WALLSMATERIAL_MODE     0.508408
EMERGENCYSTATE_MODE    0.473983
dtype: float64

In [334]:
na_cols_pctg_test = test[test.columns[test.isna().sum() > 0]].isna().sum() / test.shape[0]
na_cols_pctg_test

NAME_TYPE_SUITE        0.018689
OCCUPATION_TYPE        0.320142
FONDKAPREMONT_MODE     0.672842
HOUSETYPE_MODE         0.484552
WALLSMATERIAL_MODE     0.490173
EMERGENCYSTATE_MODE    0.455625
dtype: float64

### Drop text features Na rows

In [335]:
train = train.dropna(axis=0)

In [336]:
train.shape

(65789, 121)

In [337]:
test = test.dropna(axis=0)

In [338]:
test.shape

(10468, 120)

## Encoding categorical data

### Encoding the independent variables

In [339]:
# Get textual columns indexes
txt_cols_train = train.select_dtypes('object').columns
txt_indexes_train = train.columns.get_indexer(txt_cols_train)
txt_indexes_train

array([ 0,  1,  2,  3,  9, 10, 11, 12, 13, 26, 30, 38, 84, 85, 87, 88])

In [340]:
txt_cols_test = test.select_dtypes('object').columns
txt_indexes_test = test.columns.get_indexer(txt_cols_test)
txt_indexes_test

array([ 0,  1,  2,  3,  9, 10, 11, 12, 13, 26, 30, 38, 84, 85, 87, 88])

In [341]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
X_train = train.iloc[:, :-1].values
for i in txt_indexes_train:
  X_train[:, i] = label_encoder_x.fit_transform(X_train[:, i])
train.iloc[:, :-1] = X_train
train.head()

NAME_CONTRACT_TYPE  CODE_GENDER  ...  AMT_REQ_CREDIT_BUREAU_YEAR  TARGET
0                    0            1  ...                         1.0       1
1                    0            0  ...                         0.0       0
13                   0            1  ...                         1.0       0
14                   0            0  ...                         1.0       0
18                   1            0  ...                         0.0       0

[5 rows x 121 columns]

In [342]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
X_test = test.iloc[:, :].values
for i in txt_indexes_test:
  X_test[:, i] = label_encoder_x.fit_transform(X_test[:, i])
test.iloc[:, :] = X_test
test.head()

NAME_CONTRACT_TYPE  ...  AMT_REQ_CREDIT_BUREAU_YEAR
3                    0  ...                         3.0
5                    0  ...                         2.0
15                   0  ...                         3.0
18                   0  ...                         4.0
20                   0  ...                         2.0

[5 rows x 120 columns]

### Encoding the dependent variable

#### Checking target possible values

In [343]:
train['TARGET'].unique()

array([1, 0])

The categorical target variable can only take two values : **0** and **1**, thus no further encoding is required

## Feature scaling

In [344]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # standardization implies values between approximately -3 and 3
X_train = train.iloc[:, :-1].values
X_train[:, num_cols_train] = sc.fit_transform(X_train[:, num_cols_train]) # we don't standardize encoded textual dimensions.
train.iloc[:, :-1] = X_train
train.head()

NAME_CONTRACT_TYPE  CODE_GENDER  ...  AMT_REQ_CREDIT_BUREAU_YEAR  TARGET
0                  0.0          1.0  ...                   -0.425172       1
1                  0.0          0.0  ...                   -1.004679       0
13                 0.0          1.0  ...                   -0.425172       0
14                 0.0          0.0  ...                   -0.425172       0
18                 1.0          0.0  ...                   -1.004679       0

[5 rows x 121 columns]

In [345]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # standardization implies values between approximately -3 and 3
X_test = test.iloc[:, :].values
X_test[:, num_cols_test] = sc.fit_transform(X_test[:, num_cols_test]) # we don't standardize encoded textual dimensions.
test.iloc[:, :] = X_test
test.head()

NAME_CONTRACT_TYPE  ...  AMT_REQ_CREDIT_BUREAU_YEAR
3                  0.0  ...                    0.649564
5                  0.0  ...                    0.052319
15                 0.0  ...                    0.649564
18                 0.0  ...                    1.246809
20                 0.0  ...                    0.052319

[5 rows x 120 columns]

## Feature selection

### Removing features with at least 50% Na values (percentage computed from train set)

In [346]:
dropped_cols = na_cols_pctg_train[na_cols_pctg_train >= 0.5].axes[0].tolist()
train = train.drop(dropped_cols, axis=1)
train.shape

(65789, 118)

In [347]:
test = test.drop(dropped_cols, axis=1)
test.shape

(10468, 117)

### Removing features with a modality that appears with a probability of at least 80%

In [348]:
PROBABILITY_THRESHOLD = 0.8
train_without_target = train.drop('TARGET', axis=1)
cols_train = train_without_target.columns.tolist()
cols_to_drop_train = []
for col in cols_train:
  mods_pctg = train_without_target[col].value_counts() / train_without_target[col].value_counts().sum()
  for pctg in mods_pctg:
    if pctg >= PROBABILITY_THRESHOLD:
      cols_to_drop_train.append(col)
train = train.drop(cols_to_drop_train, axis=1)
train.shape

(65789, 78)

In [349]:
test = test.drop(cols_to_drop_train, axis=1)
test.shape

(10468, 77)

### Performing PCA

In [350]:
#from sklearn.preprocessing import StandardScaler
#from sklearn.decomposition import PCA
#from sklearn.pipeline import Pipeline
#import matplotlib.pyplot as plt

#train_array = train.drop('TARGET',axis=1).values
#pca = PCA().fit(train_array)
#plt.plot(np.cumsum(pca.explained_variance_ratio_))
#plt.xlabel('number of components')
#plt.ylabel('cumulative explained variance')

In [351]:
#pipe = Pipeline([('scaler', StandardScaler()), ('acp', PCA(n_components=5))])
#train_pca = pipe.fit_transform(train_array)
#train_pca.shape

### Removing features with a positive / negative correlation of at least 80%

In [352]:
#train_cols = train.columns
#correlation = train.corr(method="pearson")
#target_corrs = correlation['TARGET']
#[corr for corr in target_corrs if corr >= 0.2 or corr <= -0.1]


# List of new correlations
#new_corrs = []

# Iterate through the columns 
#for col in train_cols:
    # Calculate correlation with the target
#    corr = train['TARGET'].corr(train[col])
    # Append the list as a tuple
#    new_corrs.append(corr)
#[corr for corr in new_corrs if corr >= 0.1 or corr <= -0.1]

## Preprocessed data export to CSV

In [353]:
train.to_csv('preprocessed_application_train.csv', index=False)
test.to_csv('preprocessed_application_test.csv', index=False)