# Data preprocessing

## Importing the libraries

In [276]:
import pandas as pd
import numpy as np

## Create train and test dataframes

In [277]:
train = pd.read_csv('./application_train.csv')

In [278]:
test = pd.read_csv('application_test.csv')

## Display dataframes first lines

In [279]:
train.head()

SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0

[5 rows x 122 columns]

In [280]:
test.head()

SK_ID_CURR  ... AMT_REQ_CREDIT_BUREAU_YEAR
0      100001  ...                        0.0
1      100005  ...                        3.0
2      100013  ...                        4.0
3      100028  ...                        3.0
4      100038  ...                        NaN

[5 rows x 121 columns]

## Moving target to last column in train dataset

In [281]:
target_col = train.pop('TARGET')
train['TARGET'] = target_col

## Checking target possible values

In [282]:
train['TARGET'].unique()

array([1, 0])

## Taking care of missing data

In [283]:
train.shape

(307511, 122)

In [284]:
test.shape

(48744, 121)

In [285]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x_dtypes_train = train.dtypes[:-1]
num_cols_train = x_dtypes_train == np.number
X_train = train.iloc[:, :-1].values
imputer.fit(X_train[:, num_cols_train])
X_train[:, num_cols_train] = imputer.transform(X_train[:, num_cols_train])
train.iloc[:, :-1] = X_train
train.head()

SK_ID_CURR NAME_CONTRACT_TYPE  ... AMT_REQ_CREDIT_BUREAU_YEAR TARGET
0      100002         Cash loans  ...                   1.000000      1
1      100003         Cash loans  ...                   0.000000      0
2      100004    Revolving loans  ...                   0.000000      0
3      100006         Cash loans  ...                   1.899974      0
4      100007         Cash loans  ...                   0.000000      0

[5 rows x 122 columns]

In [286]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x_dtypes_test = test.dtypes
num_cols_test = x_dtypes_test == np.number
X_test = test.iloc[:, :].values
imputer.fit(X_test[:, num_cols_test])
X_test[:, num_cols_test] = imputer.transform(X_test[:, num_cols_test])
test.iloc[:, :] = X_test
test.head()

SK_ID_CURR  ... AMT_REQ_CREDIT_BUREAU_YEAR
0      100001  ...                   0.000000
1      100005  ...                   3.000000
2      100013  ...                   4.000000
3      100028  ...                   3.000000
4      100038  ...                   1.983769

[5 rows x 121 columns]

### Get text features Na rows percentage

In [287]:
train[train.columns[train.isna().sum() > 0]].isna().sum() / train.shape[0]

NAME_TYPE_SUITE        0.004201
OCCUPATION_TYPE        0.313455
FONDKAPREMONT_MODE     0.683862
HOUSETYPE_MODE         0.501761
WALLSMATERIAL_MODE     0.508408
EMERGENCYSTATE_MODE    0.473983
dtype: float64

In [288]:
test[test.columns[test.isna().sum() > 0]].isna().sum() / test.shape[0]

NAME_TYPE_SUITE        0.018689
OCCUPATION_TYPE        0.320142
FONDKAPREMONT_MODE     0.672842
HOUSETYPE_MODE         0.484552
WALLSMATERIAL_MODE     0.490173
EMERGENCYSTATE_MODE    0.455625
dtype: float64

### Drop text features Na rows

In [289]:
train = train.dropna(axis=0)

In [290]:
train.shape

(65789, 122)

In [291]:
test = test.dropna(axis=0)

In [292]:
test.shape

(10468, 121)

## Encoding categorical data

### Encoding the independent variables

In [293]:
# Get textual columns indexes
txt_cols_train = train.select_dtypes('object').columns
txt_indexes_train = train.columns.get_indexer(txt_cols_train)
txt_indexes_train

array([ 1,  2,  3,  4, 10, 11, 12, 13, 14, 27, 31, 39, 85, 86, 88, 89])

In [294]:
txt_cols_test = test.select_dtypes('object').columns
txt_indexes_test = test.columns.get_indexer(txt_cols_test)
txt_indexes_test

array([ 1,  2,  3,  4, 10, 11, 12, 13, 14, 27, 31, 39, 85, 86, 88, 89])

In [295]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
X_train = train.iloc[:, :-1].values
for i in txt_indexes_train:
  X_train[:, i] = label_encoder_x.fit_transform(X_train[:, i])
train.iloc[:, :-1] = X_train
train.head()

SK_ID_CURR  NAME_CONTRACT_TYPE  ...  AMT_REQ_CREDIT_BUREAU_YEAR  TARGET
0       100002                   0  ...                    1.000000       1
1       100003                   0  ...                    0.000000       0
13      100017                   0  ...                    1.000000       0
14      100018                   0  ...                    1.899974       0
18      100022                   1  ...                    0.000000       0

[5 rows x 122 columns]

In [296]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
X_test = test.iloc[:, :-1].values
for i in txt_indexes_test:
  X_test[:, i] = label_encoder_x.fit_transform(X_test[:, i])
test.iloc[:, :-1] = X_test
test.head()

SK_ID_CURR  ...  AMT_REQ_CREDIT_BUREAU_YEAR
3       100028  ...                         3.0
5       100042  ...                         2.0
15      100107  ...                         3.0
18      100128  ...                         4.0
20      100150  ...                         2.0

[5 rows x 121 columns]

## Feature scaling

In [297]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # standardization implies values between approximately -3 and 3
X_train = train.iloc[:, :-1].values
X_train[:, num_cols_train] = sc.fit_transform(X_train[:, num_cols_train]) # we don't standardize encoded textual dimensions.
train.iloc[:, :-1] = X_train
train.head()

SK_ID_CURR  NAME_CONTRACT_TYPE  ...  AMT_REQ_CREDIT_BUREAU_YEAR  TARGET
0     100002.0                 0.0  ...                   -0.495679       1
1     100003.0                 0.0  ...                   -1.082640       0
13    100017.0                 0.0  ...                   -0.495679       0
14    100018.0                 0.0  ...                    0.032570       0
18    100022.0                 1.0  ...                   -1.082640       0

[5 rows x 122 columns]

In [298]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() # standardization implies values between approximately -3 and 3
X_test = test.iloc[:, :].values
X_test[:, num_cols_test] = sc.fit_transform(X_test[:, num_cols_test]) # we don't standardize encoded textual dimensions.
test.iloc[:, :] = X_test
test.head()

SK_ID_CURR  ...  AMT_REQ_CREDIT_BUREAU_YEAR
3     100028.0  ...                    0.650684
5     100042.0  ...                    0.053408
15    100107.0  ...                    0.650684
18    100128.0  ...                    1.247960
20    100150.0  ...                    0.053408

[5 rows x 121 columns]

## Dimension reduction